import SpectralRadiusUpperTail.ConditionalMean

namespace SpectralRadiusUpperTail
open MeasureTheory
open scoped MeasureTheory
variable {Ω Θ E : Type*} [mΩ : MeasurableSpace Ω] [mΘ : MeasurableSpace Θ]
  [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]

/-- An actual joint-law identity transports an integrable conditional-zero
statement to the sigma-algebra generated by the same history on the source space. -/
theorem condExp_pullback_eq_zero (P : Measure Ω) [IsFiniteMeasure P]
    (Q : Measure Θ) [IsFiniteMeasure Q] (T : Ω → Θ) (hT : Measurable T)
    (hmap : P.map T = Q) (m : MeasurableSpace Θ) (hm : m ≤ mΘ)
    (f : Θ → E) (hf : Integrable f Q) (hz : Q[f | m] =ᵐ[Q] 0) :
    Integrable (f ∘ T) P ∧
      P[f ∘ T | MeasurableSpace.comap T m] =ᵐ[P] 0 := by
  letI : MeasurableSpace Θ := mΘ
  have hi : Integrable f (P.map T) := by rw [hmap]; exact hf
  have hc := hi.comp_measurable hT
  refine ⟨hc, ?_⟩
  have hle : MeasurableSpace.comap T m ≤ mΩ :=
    (MeasurableSpace.comap_mono hm).trans hT.comap_le
  symm
  refine ae_eq_condExp_of_forall_setIntegral_eq hle hc ?_ ?_ ?_
  · intro A _ _
    exact integrableOn_zero
  · intro A hA _
    rcases MeasurableSpace.measurableSet_comap.mp hA with ⟨B,hB,rfl⟩
    have hchange := setIntegral_map (μ := P) (hm _ hB) hi.aestronglyMeasurable hT.aemeasurable
    rw [hmap] at hchange
    simp only [Pi.zero_apply, integral_zero]
    change 0 = ∫ x in T ⁻¹' B, f (T x) ∂P
    rw [← hchange, ← setIntegral_condExp hm hf hB]
    rw [integral_congr_ae (ae_restrict_of_ae hz)]
    simp
  · exact aestronglyMeasurable_const

#print axioms condExp_pullback_eq_zero
end SpectralRadiusUpperTail
